### ISSUE TITLE
Running error on ESP32

### ISSUE THREAD

**Issue by Blaze-Leo** [mackorone/mms#26]
I know that the arduino version must work as long it is an ATmega. But somehow it doesnot work on the `ESP32 `even though it works on my `Arduino Mega.` The `ESP32`works correctly, but all the simulator shows is `RUNNING`. What am I doing wrong?

**Comment by mackorone** [comment]
Hmm... I'm unfamiliar with the ESP32 system. If it's not working with the code in the [`mackorone/mms-arduino`](https://github.com/mackorone/mms-arduino) repository, you may need to develop you're own code for using it with the simulator. My advice would be to play around with sending and receiving data from the board *before* trying to integrate it with the simulator. For example, can you run your "main" program and manually communicate with the process running on the board via stdin/stdout? If so, great! If not, that's the first thing to debug.

Since this issue isn't debuggable by me (I don't own an ESP32 board) I'm going to close this issue for now. Feel free to reopen if you think something about the simulator needs to be fixed, or if you write your own library and would like me to include a link to in within the repo's `README.md`.

**Comment by Blaze-Leo** [comment]
The thing is that its working but not every time. When I use the Arduino, suppose if i upload the code today and run it tomorrow, it runs just fine. But, for the ESP32 if I upload it right now, and  try to make it work it just runs sometimes,  and once it has worked once, it just doesn't connect with the computer again.

**Comment by kthompson4344** [comment]
The Arduino code in [mackorone/mms-arduino](https://github.com/mackorone/mms-arduino) assumes that when a serial connection from the simulator is established the Arduino will reset (which is the behavior of most Arduino compatible boards). I have Seeeduino XIAO that I tested that does reset upon opening a serial connection and it behaves as you described where it will work once but then will not work further. So a few questions that may help narrow down the issue:
1. What ESP32 board are you using?
2. If you reboot or reset manually each time then run it from the simulator does it work?
3. Does adding `while (!Serial);` after line 2 of mms-arduino.ino help?
