### ISSUE TITLE
How to configure start position for second run?

### ISSUE THREAD

**Issue by sanketpatel91** [mackorone/mms#39]
Thank you for great simulator.

I am using mms-arduino and **mms.exe** from windows.zip in released version.
Directory:  C:\Users\User1\Desktop\Maze-Solver-Robot\mms-arduino
Run command:  C:\Users\User1\Desktop\Python311\python.exe Main.py --port COM8 --baud 19200

First Run is **successful** using Arduino Uno board and mouse reached to Goal location.
Now I need to move mouse to start location again in mms.exe to start Second time Run. How can I put mouse again to location (0,0) to check Second run.

**Comment by mackorone** [comment]
@sanketpatel91 I'm happy the simulator has been useful to you :).

> How can I put mouse again to location (0,0) to check Second run.

Great question! This is exactly what the "Reset" button the UI was designed to do. Prior to clicking that button, the simulator will respond to `wasReset` messages with `false`. Upon clicking that button, the simulator will respond to `wasReset` messages with `true` - that's how you can determine that someone clicked the button. Then, to actually reset the position of the mouse in the virtual maze, you can send the `ackReset` message to the simulator. 

Here's the relevant code from [mackorone/mackalgo](https://github.com/mackorone/mackalgo), which properly handles resets: https://github.com/mackorone/mackalgo/blob/master/src/Algo.cpp#L96-L102

Note that since you're running your algorithm code on a physical Arduino board, you may need think carefully about the sequence of events. Here's one way to do it:

1. Press the "RESET" button on your Arduino board to indicate to your algorithm that the mouse is about to be reset
2. Upon restarting, your algorithm should sleep for a few seconds, to give you time to do the next step...
3. Press the "Reset" button in the simulator, to simulate moving the mouse back to the start
4. Once your algorithm is done sleeping, send the `ackReset` message to update the position of the mouse

Hope that helps. Good luck!

**Comment by sanketpatel91** [comment]
@mackorone: Thank you for response.

As per algorithm code on a physical Arduino board, there is a 30 second wait after reaching destination in first run, then micro mouse should be moved to start position (0,0) within 30 seconds and then second run should start.

If I press Reset button on Arduino, then we might lose all wall information and path information.
So, is there any other way to put mouse again to location (0,0) to check Second run in mms?

**Comment by mackorone** [comment]
@sanketpatel91 if your code sleeps for 30 seconds after the initial run, then all you need to do is:

1. Click the "Reset" button in the simulator within those 30 seconds
2. Send an `ackReset` message to the simulator when you wake up from the sleep, which will reset the mouse position

Good luck!

**Comment by sanketpatel91** [comment]
@mackorone : Thank you for the information.
calling ackReset() during the 30s delay solved the issue and mouse moves to start position.
